apiVersion: v1
kind: Service
metadata:
  name: xero-integration
  labels:
    app: xero-integration
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: xero-integration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xero-integration
  labels:
    app: xero-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xero-integration
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: xero-integration
    spec:
      containers:
      - name: xero-integration
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/xero-integration:imgtag
        resources:
          requests:
            memory: "200Mi"
            cpu: "49m"
          limits:
            memory: "400Mi"
        envFrom:
        - configMapRef:
            name: common-services-config
        ports: 
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config-file
          mountPath: "/app/application-staging.yml"  # "secret-file" file will be created in "/app" directory
          subPath: application.yml
        - name: tz-lagos
          mountPath: /etc/localtime
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/description
                operator: In
                values:
                - staging
                - wayabank-staging    
      volumes:
        - name: config-file
          secret:
            secretName: xero-integration-config-file # name of the Secret
        - name: tz-lagos
          hostPath:
            path: /usr/share/zoneinfo/Africa/Lagos
